# Generated by Django 3.2 on 2024-02-29 14:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Collect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('event', models.CharField(choices=[('Birthday', 'День рождения'), ('Wedding', 'Свадьба'), ('Date', 'Свидание'), ('Gift', 'Подарок'), ('Homeless animals', 'Бездомным котикам и пёсикам'), ('Charity', 'Благотворительность'), ('Other', 'Другое')], max_length=200)),
                ('description', models.TextField(max_length=10000)),
                ('goal_sum', models.IntegerField(blank=True, default=None, null=True)),
                ('cover', models.ImageField(blank=True, null=True, upload_to='collects/')),
                ('end_date', models.DateTimeField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collects', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата платежа')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL)),
                ('collect', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='collects.collect')),
            ],
        ),
    ]
